<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="MongoDB.Driver" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="RabbitMQ.Client" />
        <PackageReference Include="Serilog" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Esperanca.Campanha.Application\Esperanca.Campanha.Application.csproj" />
    </ItemGroup>

</Project>